from django.db import models

# Create your models here.
COMMUNITYAREA = (
    ('14', 'Albany Park'),
    ('57', 'Archer Heights'),
    ('34', 'Armour Square'),
    ('70', 'Ashburn'),
    ('71', 'Auburn Gresham'),
    ('25', 'Austin'),
    ('45', 'Avalon Park'),
    ('21', 'Avondale'),
    ('19', 'Belmont Cragin'),
    ('72', 'Beverky'),
    ('60', 'Bridgeport'),
    ('58', 'Brighton Park'),
    ('47', 'Burnside'),
    ('48', 'Calumet Heights'),
    ('44', 'Chatham'),
    ('66', 'Chicago Lawn'),
    ('64', 'Clearing'),
    ('35', 'Douglas'),
    ('17', 'Dunning'),
    ('27', 'East Garfield Park'),
    ('52', 'East Side'),
    ('77', 'Edgewater'),
    ('09', 'Edison Park'),
    ('68', 'Englewood'),
    ('12', 'Forest Glen'),
    ('37', 'Fuller Park'),
    ('63', 'Gage Park'),
    ('56', 'Garfield Ridge'),
    ('38', 'Grand Boulevard'),
    ('69', 'Greater Grand Crossing'),
    ('55', 'Hagewisch'),
    ('20', 'Hermosa'),
    ('23', 'Humboldt Park'),
    ('41', 'Hyde Park'),
    ('16', 'Irving Park'),
    ('11', 'Jefferson Park'),
    ('39', 'Kenwood'),
    ('06', 'Lake View'),
    ('07', 'Lincoln Park'),
    ('04', 'Lincoln Square'),
    ('22', 'Logan Square'),
    ('32', 'Loop'),
    ('31', 'Lower West Side'),
    ('59', 'McKinley Parl'),
    ('18', 'Montclare'),
    ('75', 'Morgan Park'),
    ('74', 'Mount Grenwood'),
    ('08', 'Near North Side'),
    ('33', 'Near South Side'),
    ('28', 'Near West Side'),
    ('61', 'New City'),
    ('05', 'North Center'),
    ('29', 'North Lawndale'),
    ('13', 'North Park'),
    ('10', 'Norwood Park'),
    ('36', 'Oakland'),
    ('76', "O'Hare"),
    ('15', 'Portage Park'),
    ('50', 'Pullman'),
    ('54', 'Riverdale'),
    ('01', 'Rogers Park'),
    ('49', 'Roseland'),
    ('46', 'South Chicago'),
    ('51', 'South Deering'),
    ('30', 'South Lawndale'),
    ('43', 'South Shore'),
    ('03', 'Uptown'),
    ('73', 'Washington Heights'),
    ('40', 'Washington Park'),
    ('67', 'West Englewood'),
    ('62', 'West Elsdon'),
    ('26', 'West Garfield Park'),
    ('65', 'West Lawn'),
    ('53', 'West Pullman'),
    ('02', 'West Ridge'),
    ('24', 'West Town'),
    ('42', 'Woodlawn'),
    ('F', '')
   )

COMMUNITYAREA_DICT = dict(COMMUNITYAREA)

class Input(models.Model):

    communityarea = models.CharField(max_length=2, choices=COMMUNITYAREA)
    name  = models.CharField(max_length=50)
